# Generated by Django 5.2.4 on 2025-08-03 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_account_id', models.CharField(help_text='Google account unique identifier', max_length=100)),
                ('email', models.EmailField(help_text='Google account email address', max_length=254)),
                ('access_token', models.TextField(help_text='Encrypted OAuth access token')),
                ('refresh_token', models.TextField(help_text='Encrypted OAuth refresh token')),
                ('token_expires_at', models.DateTimeField(help_text='When the access token expires')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable sync for this account')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calendar Account',
                'verbose_name_plural': 'Calendar Accounts',
                'unique_together': {('user', 'google_account_id')},
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_calendar_id', models.CharField(help_text='Google Calendar unique identifier', max_length=200)),
                ('name', models.CharField(help_text='Calendar display name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Calendar description')),
                ('color', models.CharField(blank=True, help_text='Calendar color code', max_length=10)),
                ('is_primary', models.BooleanField(default=False, help_text='Is this the primary calendar for the account')),
                ('sync_enabled', models.BooleanField(default=True, help_text='Enable/disable sync for this calendar')),
                ('last_sync_token', models.CharField(blank=True, help_text='Token for incremental sync', max_length=500)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Last successful sync timestamp', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='calendars.calendaraccount')),
            ],
            options={
                'verbose_name': 'Calendar',
                'verbose_name_plural': 'Calendars',
                'unique_together': {('calendar_account', 'google_calendar_id')},
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('full', 'Full Sync'), ('incremental', 'Incremental Sync'), ('manual', 'Manual Sync')], default='incremental', max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('partial', 'Partial Success'), ('in_progress', 'In Progress')], default='in_progress', max_length=20)),
                ('events_processed', models.PositiveIntegerField(default=0, help_text='Total events processed')),
                ('events_created', models.PositiveIntegerField(default=0, help_text='New events created')),
                ('events_updated', models.PositiveIntegerField(default=0, help_text='Events updated')),
                ('events_deleted', models.PositiveIntegerField(default=0, help_text='Events deleted')),
                ('busy_blocks_created', models.PositiveIntegerField(default=0, help_text='Busy blocks created')),
                ('busy_blocks_updated', models.PositiveIntegerField(default=0, help_text='Busy blocks updated')),
                ('busy_blocks_deleted', models.PositiveIntegerField(default=0, help_text='Busy blocks deleted')),
                ('error_message', models.TextField(blank=True, help_text='Error details if sync failed')),
                ('api_calls_made', models.PositiveIntegerField(default=0, help_text='Number of Google API calls made')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When sync completed (success or failure)', null=True)),
                ('calendar_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='calendars.calendaraccount')),
            ],
            options={
                'verbose_name': 'Sync Log',
                'verbose_name_plural': 'Sync Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_event_id', models.CharField(help_text='Google Calendar event unique identifier', max_length=200)),
                ('title', models.CharField(help_text='Event title/summary', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Event description')),
                ('start_time', models.DateTimeField(help_text='Event start datetime (UTC)')),
                ('end_time', models.DateTimeField(help_text='Event end datetime (UTC)')),
                ('is_all_day', models.BooleanField(default=False, help_text='All-day event flag')),
                ('is_busy_block', models.BooleanField(default=False, help_text='System-created busy block flag')),
                ('busy_block_tag', models.CharField(blank=True, help_text='Unique tag for busy block identification', max_length=200)),
                ('event_hash', models.CharField(blank=True, help_text='Hash of event content for change detection', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='calendars.calendar')),
                ('source_event', models.ForeignKey(blank=True, help_text='Source event for busy blocks', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='busy_blocks', to='calendars.event')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['start_time'],
                'unique_together': {('calendar', 'google_event_id')},
            },
        ),
    ]
