# Generated by Django 5.2.4 on 2025-08-03 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='name',
            field=models.CharField(help_text='Calendar display name', max_length=200, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Event title/summary', max_length=500, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AddIndex(
            model_name='calendar',
            index=models.Index(fields=['last_synced_at'], name='calendars_c_last_sy_f373a7_idx'),
        ),
        migrations.AddIndex(
            model_name='calendar',
            index=models.Index(fields=['sync_enabled'], name='calendars_c_sync_en_1033cc_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_time', 'end_time'], name='calendars_e_start_t_ff8439_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_busy_block'], name='calendars_e_is_busy_623a07_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['source_event'], name='calendars_e_source__429658_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['updated_at'], name='calendars_e_updated_b0a8bb_idx'),
        ),
    ]
