# Generated by Django 5.2.4 on 2025-08-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='cleanup_pending',
            field=models.BooleanField(default=False, help_text='Calendar cleanup operation pending'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='cleanup_requested_at',
            field=models.DateTimeField(blank=True, help_text='When cleanup was requested', null=True),
        ),
        migrations.AddIndex(
            model_name='calendar',
            index=models.Index(fields=['cleanup_pending'], name='calendars_c_cleanup_ee9cbc_idx'),
        ),
    ]
