# Generated by Django 5.2.4 on 2025-08-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_add_cleanup_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='calendar',
            name='calendars_c_cleanup_ee9cbc_idx',
        ),
        migrations.AddIndex(
            model_name='calendar',
            index=models.Index(condition=models.Q(('cleanup_pending', True)), fields=['cleanup_pending', 'updated_at'], name='idx_cleanup_pending_with_time'),
        ),
    ]
