# Generated by Django 5.2.4 on 2025-08-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_alter_calendar_name_alter_event_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_meeting_invite',
            field=models.BooleanField(default=False, help_text='Whether this event is a meeting invite (has attendees)'),
        ),
    ]
