# Generated by Django 5.2.4 on 2025-08-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0003_add_meeting_invite_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='webhook_channel_id',
            field=models.CharField(blank=True, help_text='Google webhook channel ID for this calendar', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='webhook_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the webhook subscription expires', null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='webhook_last_setup',
            field=models.DateTimeField(blank=True, help_text='When webhook was last registered with Google', null=True),
        ),
    ]
